name: Linux Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Linux Build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: sudo apt-get install vlc libvlc-dev libvlccore-dev vlc-bin
        run: sh ./setup/install-haxelibs.sh

      - name: Build for Linux
        run: haxelib run lime build linux

      - name: Upload Game
        uses: actions/upload-artifact@main
        with:
          name: Linux Build
          path: export/release/linux/bin