name: Windows Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: setup/install-haxelibs.bat

      - name: Build for Windows
        run: haxelib run lime build windows

      - name: Upload Game
        uses: actions/upload-artifact@main
        with:
          name: Windows Build
          path: export/release/windows/bin